[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 2"
restartPolicyType = "always"
restartPolicyMaxRetries = 3

[healthcheck]
path = "/"
interval = 30

[[services]]
name = "web"
port = 5000